version: "3"

services:
  web:
    container_name: "next-app"
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - next-app
  db:
    container_name: "mongo-db"
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - wholesalerbase:/data/db
    networks:
       - next-app
volumes:
 wholesalerbase: 

networks:
  next-app:
    driver: bridge

# version: '3.8'
# services:

#   api:
#     build: ./backend
#     ports:
#       - 3001:3001

